Sync precice develop
precice/PreCICE.jl pull request #47
Opened 2023-01-05 11:37 UTC by erikscheurer

This PR synchs the Julia bindings' develop branch to precice/precice.
The included changes are taken from the precice changelog and are breaking as the precice containers are not compatible with the new implementation

2023-01-11 08:25 UTC, IshaanDesai commented
Discussed with @erikscheurer and we concluded that tests need to use precice:develop and not the latest release of preCICE.

2023-03-14 11:54 UTC, IshaanDesai commented on solverdummy/solverdummy.jl
> +dimensions = PreCICE.ge
?

2023-03-14 11:58 UTC, IshaanDesai commented on src/PreCICE.jl
> +function getDataID(dataName::String, meshName::String)
Data IDs no longer exist, so this function needs to be removed.

2023-03-14 13:06 UTC, erikscheurer commented on solverdummy/solverdummy.jl
> +dimensions = PreCICE.ge
This was a weird VS code bug

2023-03-14 13:41 UTC, IshaanDesai requested changes
Modifications to the already existing functions look to be in order :+1: ~~Some API functions are missing and need to be implemented. For reading data, we now have variants of all API functions for the waveform relaxation, meaning we can read data at a specific time point. An example can be seen here:~~

~~https://github.com/precice/precice/blob/bbee6400bbffda726c4d72a58134b81b3c6ccca2/src/precice/SolverInterface.cpp#L272-L291~~

~~Please look at these variants in the C++ API and implement them here.~~

Adding new API functions will be handled in separate PRs.

2023-03-16 07:07 UTC, IshaanDesai commented on src/PreCICE.jl
> +    )
Is this a formatting change? Similar changes are seen below, and it seems that nothing is changing code-wise.

2023-03-16 07:09 UTC, IshaanDesai approved these changes

2023-03-16 07:11 UTC, merged