Add missing API functions
precice/PreCICE.jl pull request #50
Opened 2023-03-18 18:20 UTC by erikscheurer

This PR adds functions that are missing from the [preCICE API](https://github.com/precice/precice/blob/develop/src/precice/SolverInterface.hpp).

This includes:
- Functions for multiple Edges, Triangles, Quads
- `setMeshTetrahedron` and `setMeshTetrahedra`
- `requiresMeshConnectivityFor`, `setMeshAccessRegion`, `getMeshVerticesAndIDs`
- Optional argument `relativ_read_time` for waveform iteration.

The realization of the last point is still up for discussion. At the moment, I have an optional argument as -1.0 and a case distinction in the function itself which I think is not ideal. 
In the [python bindings](https://github.com/precice/python-bindings/blob/02f43d8de0ab87480735975ab8708ecbf00e049b/cyprecice/cyprecice.pyx#L879-L942) the optional argument is `None`, however, in Julia, if you do this, you can't give the argument Type as `Float64` because `nothing` is of type `Nothing`.
Another option is to simply use multiple dispatch for the function, so create multiple functions just like in the API, however, I did not get this to work at the moment. Trying to run the solverdummies, they could not find the correct function when the functioncall is separated.

2023-03-23 08:41 UTC, IshaanDesai commented on src/PreCICE.jl
> +    @assert dimensions == 2 "Dimensions of vector data in write_vector_data does not match with dimensions in problem definition. Provided dimensions: $dimensions, expected dimensions: $(getDimension
Assertion message seems like a left over from copy pasting. Lets write a more sensible message here. For example, *Vertices pairs need to be provided while setting mesh edges. Please check the shape of the vertices array*.

2023-03-23 08:42 UTC, IshaanDesai commented on src/PreCICE.jl
> +    @assert dimensions == 3 "Dimensions of vector data in write_vector_data does not match with dimensions in problem definition. Provided dimensions: $dimensions, expected dimensions: $(getDimension
Same as above.

2023-03-23 08:45 UTC, IshaanDesai commented on src/PreCICE.jl
> +    @assert dimensions == 4 "Dimensions of vector data in write_vector_data does not match with dimensions in problem definition. Provided dimensions: $dimensions, expected dimensions: $(getDimension
Same as the previous comment for edges.

2023-03-23 08:49 UTC, IshaanDesai commented on src/PreCICE.jl
> +    @assert dimensions == 4 "Dimensions of vector data in write_vector_data does not match with dimensions in problem definition. Provided dimensions: $dimensions, expected dimensions: $(getDimension
Same as above. Also lets find a better name for the variable than **dimensions**.

2023-03-23 08:55 UTC, IshaanDesai commented on src/PreCICE.jl
> +Read and return vector data values given as block.
```suggestion
Read and return vector data values given as block.
```

2023-03-23 09:01 UTC, IshaanDesai commented on src/PreCICE.jl
>      return permutedims(reshape(values, (getDimensions(), _size)))
Why do we return something for a read operation?

2023-03-23 09:01 UTC, IshaanDesai commented on src/PreCICE.jl
> +    readVectorData(meshName::String, dataName::String, valueIndex::Integer[, relative_read_time::Float64])::AbstractArray{Float64}
Same concern as above.

2023-03-23 09:05 UTC, IshaanDesai requested changes
Looks good already :+1: some comments from my side.

2023-03-23 09:24 UTC, erikscheurer commented on src/PreCICE.jl
> +    readBlockVectorData(meshName::String, dataName::String, valueIndices::AbstractArray{Cint}[, relative_read_time::Float64])
Yes, as long as there is no default value (which in our case semantically is not) this is the [correct](https://docs.julialang.org/en/v1/manual/documentation/#Writing-Documentation) syntax.

2023-03-23 11:38 UTC, IshaanDesai commented on .github/workflows/build-and-test.yml
> +        julia-version: ["1.6.7", "1.7", "^1.8"]
Okay got it :+1: sounds very reasonable.

2023-03-24 13:51 UTC, IshaanDesai approved these changes

2023-03-24 13:51 UTC, merged